# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.4.0
_src_path: gh:radio-aktywne/template-database-minio
accountname: radio-aktywne
databasename: mediatunes
description: Emission playlists media 💽
docs: true
docsurl: https://radio-aktywne.github.io/database-mediatunes
envprefix: MEDIATUNES
imagename: databases/mediatunes
port: 40000
registry: true
releases: true
reponame: database-mediatunes
repourl: https://github.com/radio-aktywne/database-mediatunes
webport: 40001
